name: .NET Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # або 7.0.x, залежно від версії твого проєкту

      - name: Restore dependencies
        run: dotnet restore AutoCatalog.sln

      - name: Build
        run: dotnet build AutoCatalog.sln --no-restore --configuration Release

      - name: Run Tests
        run: dotnet test AutoCatalog.sln --no-build --logger "console;verbosity=detailed"
