name: Python CI

on:
  push:
  pull_request:

jobs:
  cyclomatic-complexity:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run Cyclomatic Complexity script
      run: python .Tests/cyclomatic_complexity.py
