name: Cyclomatic Complexity Analysis

on:
  workflow_dispatch:  # ручний запуск
  push:
    paths:
      - '.Tests/**'
      - '.github/workflows/python-app.yml'

jobs:
  cyclomatic-complexity:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Cyclomatic Complexity Analysis
        run: python3 .Tests/cyclomatic_complexity.py
